name: 'Latino traveller '
favicon: null
layout_spectrum: 0.02758525
typography_spectrum: 0.257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4365AC'
    - '#0C0F03'
    - '#FFFFC6'
    - '#CFC677'
    - '#918839'
  brandStrength: 0.3195353
  lightness: 0.9139785
  saturation: 0.7017366
  rhythmicContrast: 0.7876438
purpose: []
